In [ ]:
import pandas as pd

# **Dataset 1 — Appliances Energy Prediction (UCI)**
**Situação**

Uma empresa de eficiência energética está analisando o comportamento de uma residência de
baixo consumo. A equipe deseja identificar períodos de consumo elevado dos eletrodomésticos e
observar quais condições de temperatura e umidade estavam presentes nesses momentos.

![untitled.svg]()

In [ ]:
# Carregar a amostra
df1 = pd.read_csv('/content/energydata_complete_10.csv')

In [ ]:
# Visuailzar
df1.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3
0,2016-03-14 01:40:00,40,0,20.8900,35.4000,17.7600,39.1633,20.2900,36.9000
1,2016-01-30 20:00:00,90,10,21.8900,53.1000,21.2900,45.3600,21.6333,49.2267
2,2016-03-15 03:00:00,50,0,21.3900,35.5000,17.6333,40.5300,21.6667,35.2000
3,2016-04-20 10:10:00,50,0,21.3900,41.0333,23.8900,34.8400,22.0333,36.9333
4,2016-03-13 08:10:00,70,0,19.9633,35.1267,16.4633,40.1267,20.0000,36.4000

In [ ]:
print(f"Total de registros: {df1.shape[0]}")
print(f"Total de columas: {df1.shape[1]}")

Total de registros: 1974
Total de columas: 9

In [ ]:
# Informações dos atributos
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1974 entries, 0 to 1973
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1974 non-null   object
 1   Appliances  1974 non-null   int64
 2   lights      1974 non-null   int64
 3   T1          1974 non-null   float64
 4   RH_1        1974 non-null   float64
 5   T2          1974 non-null   float64
 6   RH_2        1974 non-null   float64
 7   T3          1974 non-null   float64
 8   RH_3        1974 non-null   float64
dtypes: float64(6), int64(2), object(1)
memory usage: 138.9+ KB

In [ ]:
# Estatísticas descritivas dos atributos numéricos
df1.describe()

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3
count,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000
mean,93.044580,3.839919,21.664703,40.219193,20.293635,40.411386,22.231615,39.209733
std,93.826149,7.937076,1.574883,3.971923,2.126958,4.037686,1.957275,3.288818
min,20.000000,0.000000,16.790000,27.733300,16.100000,24.063300,17.200000,30.133300
25%,50.000000,0.000000,20.700000,37.205825,18.790000,37.760000,20.700000,36.900000
50%,60.000000,0.000000,21.600000,39.590000,20.000000,40.433300,22.100000,38.433300
75%,100.000000,0.000000,22.600000,42.991675,21.500000,43.228325,23.290000,41.741250
max,770.000000,50.000000,26.260000,57.496700,28.917500,56.026700,29.198600,49.226700

In [ ]:
df1.rename(columns={"Appliances": "Consumo_Eletrodomesticos",
                      "T1": "Temperatura_1",
                      "T2": "Temperatura_2",
                      "T3": "Temperatra_3"}, inplace=True)

In [ ]:
# Encontrando o maior consumo
maior_consumo = df1['Consumo_Eletrodomesticos'].max()

print(maior_consumo)

770

In [ ]:
# Calculando limiar correspondente a 70%
limiar_df1 = maior_consumo * 0.70

print(limiar_df1)

539.0

In [ ]:
df1_acima_70 = df1[df1['Consumo_Eletrodomesticos'] > limiar_df1]

In [ ]:
df1_acima_70.head()

,date,Consumo_Eletrodomesticos,lights,Temperatura_1,RH_1,Temperatura_2,RH_2,Temperatra_3,RH_3
352,2016-05-26 17:10:00,620,0,24.3900,44.3333,25.3700,37.7360,26.7300,38.8633
427,2016-03-19 11:20:00,650,0,20.8900,36.7000,18.2900,39.6633,21.2000,36.0000
453,2016-03-21 18:40:00,560,30,21.3567,36.0900,19.5667,37.1633,21.6333,35.0300
616,2016-05-14 17:50:00,570,10,24.8900,32.6667,23.5600,31.1400,23.6000,30.8233
696,2016-01-21 19:10:00,590,30,19.8567,47.6633,18.7000,34.1000,18.4267,37.8333

In [ ]:
# Contar registros e calcular percentual da amostra
quantidade = len(df1_acima_70)

percentual = (quantidade / len(df1)) * 100

print("Registros acima de 70%:", quantidade)
print("Percentual da amostra:", percentual, "%")

Registros acima de 70%: 22
Percentual da amostra: 1.1144883485309016 %

In [ ]:
# Temperatura média de T1 e segundo DataFrame
temperatura_media = df1['Temperatura_1'].mean()

df1_acima_70_temp = df1[
    (df1['Consumo_Eletrodomesticos'] > limiar_df1) &
    (df1['Temperatura_1'] > temperatura_media)
]

In [ ]:
df1_acima_70_temp.head()

,date,Consumo_Eletrodomesticos,lights,Temperatura_1,RH_1,Temperatura_2,RH_2,Temperatra_3,RH_3
352,2016-05-26 17:10:00,620,0,24.3900,44.3333,25.3700,37.7360,26.73,38.8633
616,2016-05-14 17:50:00,570,10,24.8900,32.6667,23.5600,31.1400,23.60,30.8233
916,2016-02-11 18:50:00,750,30,22.4300,43.0000,21.9267,40.1333,21.23,42.5967
993,2016-02-09 19:10:00,690,10,22.5333,45.0267,22.0667,39.7900,22.39,41.9300
1182,2016-05-13 11:10:00,600,20,24.8900,48.1333,28.9175,37.9475,27.10,42.4400

In [ ]:
# Comparar os dois DataFrames
print("Somente consumo acima de 70%:", len(df1_acima_70))
print("Consumo acima de 70% + T1 acima da média:", len(df1_acima_70_temp))

Somente consumo acima de 70%: 22
Consumo acima de 70% + T1 acima da média: 8

In [ ]:
percentual_com_temperatura = (len(df1_acima_70_temp) / len(df1)) * 100

print("Percentual após adicionar temperatura:", percentual_com_temperatura, "%")

Percentual após adicionar temperatura: 0.4052684903748734 %

In [ ]:
print("DataFrame 1:")
display(df1_acima_70.head())

print("DataFrame 2:")
display(df1_acima_70_temp.head())

DataFrame 1:

,date,Consumo_Eletrodomesticos,lights,Temperatura_1,RH_1,Temperatura_2,RH_2,Temperatra_3,RH_3
352,2016-05-26 17:10:00,620,0,24.3900,44.3333,25.3700,37.7360,26.7300,38.8633
427,2016-03-19 11:20:00,650,0,20.8900,36.7000,18.2900,39.6633,21.2000,36.0000
453,2016-03-21 18:40:00,560,30,21.3567,36.0900,19.5667,37.1633,21.6333,35.0300
616,2016-05-14 17:50:00,570,10,24.8900,32.6667,23.5600,31.1400,23.6000,30.8233
696,2016-01-21 19:10:00,590,30,19.8567,47.6633,18.7000,34.1000,18.4267,37.8333

DataFrame 2:

,date,Consumo_Eletrodomesticos,lights,Temperatura_1,RH_1,Temperatura_2,RH_2,Temperatra_3,RH_3
352,2016-05-26 17:10:00,620,0,24.3900,44.3333,25.3700,37.7360,26.73,38.8633
616,2016-05-14 17:50:00,570,10,24.8900,32.6667,23.5600,31.1400,23.60,30.8233
916,2016-02-11 18:50:00,750,30,22.4300,43.0000,21.9267,40.1333,21.23,42.5967
993,2016-02-09 19:10:00,690,10,22.5333,45.0267,22.0667,39.7900,22.39,41.9300
1182,2016-05-13 11:10:00,600,20,24.8900,48.1333,28.9175,37.9475,27.10,42.4400

# **Exercicio 7**

Comparação: Ao adicionar a temperatura T1 como segundo critério, a quantidade de registros selecionados diminuiu de X para Y. Isso ocorre porque, além de apresentar consumo elevado, o registro também precisa apresentar uma temperatura acima da média. Portanto, a inclusão da temperatura torna o filtro mais restritivo.

# **Dataset 2 — Steel Industry Energy Consumption (UCI)**
**Situação**

A equipe de gestão de energia de uma indústria siderúrgica deseja localizar situações de
consumo elevado e verificar se esses períodos coincidem com condições de carga elevada ou
valores menos favoráveis de fator de potência.

![untitled.svg]()

In [ ]:
# Carregar a amostra
df2 = pd.read_csv('/content/steel_energy_amostra_20.csv')

In [ ]:
# Visuailzar
df2.head()

,date,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,Lagging_Current_Power_Factor,Leading_Current_Power_Factor,WeekStatus,Day_of_week,Load_Type
0,string,continuous,continuous,continuous,continuous,continuous,Weekday Weekend,Friday Monday Saturday Sunday Thursday Tuesday...,Light_Load Maximum_Load Medium_Load
1,meta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,06/09/2018 15:45,60.44,38.99,0.00,84.03,100.00,Weekday,Thursday,Maximum_Load
3,13/12/2018 18:45,79.63,29.88,0.00,93.63,100.00,Weekday,Thursday,Maximum_Load
4,09/07/2018 10:00,59.80,27.18,0.00,91.04,100.00,Weekday,Monday,Medium_Load

In [ ]:
print(f"Total de registros: {df2.shape[0]}")
print(f"Total de columas: {df2.shape[1]}")

Total de registros: 7010
Total de columas: 9

In [ ]:
# Informações dos atributos
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7010 entries, 0 to 7009
Data columns (total 9 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   date                                  7010 non-null   object
 1   Usage_kWh                             7009 non-null   object
 2   Lagging_Current_Reactive.Power_kVarh  7009 non-null   object
 3   Leading_Current_Reactive_Power_kVarh  7009 non-null   object
 4   Lagging_Current_Power_Factor          7009 non-null   object
 5   Leading_Current_Power_Factor          7009 non-null   object
 6   WeekStatus                            7009 non-null   object
 7   Day_of_week                           7009 non-null   object
 8   Load_Type                             7009 non-null   object
dtypes: object(9)
memory usage: 493.0+ KB

In [ ]:
# Estatísticas descritivas dos atributos numéricos
df2.describe()

,date,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,Lagging_Current_Power_Factor,Leading_Current_Power_Factor,WeekStatus,Day_of_week,Load_Type
count,7010,7009,7009,7009,7009,7009,7009,7009,7009
unique,7010,1859,1403,659,3076,1306,3,8,4
top,16/06/2018 00:00,3.06,0.00,0.00,100.00,100.00,Weekday,Wednesday,Light_Load
freq,1,141,1446,4724,1507,4904,5003,1059,3666

In [ ]:
# Renomeando
df2 = df2.rename(columns={
    'Usage_kWh': 'Consumo_kWh',
    'Lagging_Current_Power_Factor': 'Fator_Potencia_Atrasado',
    'Leading_Current_Power_Factor': 'Fator_Potencia_Adiantado',
    'Lagging_Current_Reactive.Power_kVarh': 'Potencia_Reativa_Atrasada',
    'Leading_Current_Reactive_Power_kVarh': 'Potencia_Reativa_Adiantada'
})

In [ ]:
df2.head()

,date,Consumo_kWh,Potencia_Reativa_Atrasada,Potencia_Reativa_Adiantada,Fator_Potencia_Atrasado,Fator_Potencia_Adiantado,WeekStatus,Day_of_week,Load_Type
0,string,continuous,continuous,continuous,continuous,continuous,Weekday Weekend,Friday Monday Saturday Sunday Thursday Tuesday...,Light_Load Maximum_Load Medium_Load
1,meta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,06/09/2018 15:45,60.44,38.99,0.00,84.03,100.00,Weekday,Thursday,Maximum_Load
3,13/12/2018 18:45,79.63,29.88,0.00,93.63,100.00,Weekday,Thursday,Maximum_Load
4,09/07/2018 10:00,59.80,27.18,0.00,91.04,100.00,Weekday,Monday,Medium_Load

In [ ]:
# Converter a coluna Consumo_kWh para número
df2['Consumo_kWh'] = pd.to_numeric(
    df2['Consumo_kWh'],
    errors='coerce'
)

# Encontrar o maior consumo
consumo_maximo = df2['Consumo_kWh'].max()

print(f"Maior consumo registrado: {consumo_maximo:.2f} kWh")

Maior consumo registrado: 149.65 kWh

In [ ]:
# Criando uma limiar
limiar_75_df2 = consumo_maximo * 0.75

print("Limiar de 75%:", limiar_75, "kWh")

Limiar de 75%: 112.23750000000001 kWh

In [ ]:
# Criando um novo DataFrame
df2_alto_consumo = df2[df2['Consumo_kWh'] > limiar_75_df2]

In [ ]:
df2_alto_consumo.head()

,date,Consumo_kWh,Potencia_Reativa_Atrasada,Potencia_Reativa_Adiantada,Fator_Potencia_Atrasado,Fator_Potencia_Adiantado,WeekStatus,Day_of_week,Load_Type
128,27/11/2018 10:15,129.20,56.81,0.00,91.54,100.00,Weekday,Tuesday,Maximum_Load
177,12/01/2018 09:15,130.18,50.08,0.00,93.33,100.00,Weekday,Friday,Medium_Load
271,06/02/2018 11:45,131.65,67.75,0.00,88.92,100.00,Weekday,Tuesday,Maximum_Load
353,11/09/2018 17:15,118.84,62.96,0.00,88.37,100.00,Weekday,Tuesday,Medium_Load
430,19/03/2018 09:45,116.71,52.52,0.00,91.19,100.00,Weekday,Monday,Medium_Load

In [ ]:
quantidade_alto_consumo = len(df2_alto_consumo)

print("Quantidade de registros:", quantidade_alto_consumo)

Quantidade de registros: 167

In [ ]:
# Calculando percentual de registros
percentual_alto_consumo = (quantidade_alto_consumo / len(df2)) * 100

print("Percentual de registros:", percentual_alto_consumo, "%")

Percentual de registros: 2.3823109843081314 %

In [ ]:
# Verificando a categoria Maximum Load
quantidade_maximum_load = (
    df2_alto_consumo['Load_Type'] == 'Maximum_Load'
).sum()

print("Registros de alto consumo em Maximum Load:",
      quantidade_maximum_load)

Registros de alto consumo em Maximum Load: 72

In [ ]:
# Escolhendo um fator potência
df2['Fator_Potencia_Atrasado'].describe()

count       7009
unique      3076
top       100.00
freq        1507
Name: Fator_Potencia_Atrasado, dtype: object

In [ ]:
df2['Fator_Potencia_Atrasado'].head(20)

0     continuous
1            NaN
2          84.03
3          93.63
4          91.04
5          94.37
6          99.18
7          83.16
8          91.29
9          88.53
10         89.23
11         52.23
12         57.11
13         87.31
14        100.00
15        100.00
16         89.69
17         50.92
18         48.14
19         99.78
Name: Fator_Potencia_Atrasado, dtype: object

In [ ]:
limite_fpa = 0.90

print(f"Limite escolhido para fator de potência: {limite_fpa}")

Limite escolhido para fator de potência: 0.9

In [ ]:
# Análise de consumo elevado + fator de potência baixo

# Converter as colunas para números
df2['Consumo_kWh'] = pd.to_numeric(
    df2['Consumo_kWh'], errors='coerce'
)

df2['Fator_Potencia_Atrasado'] = pd.to_numeric(
    df2['Fator_Potencia_Atrasado'], errors='coerce'
)

# Maior consumo
consumo_maximo = df2['Consumo_kWh'].max()

# Limiar de 75%
limiar_75_df2 = consumo_maximo * 0.75

# Limite do fator de potência
limite_fpa = 0.90

# Registros com consumo elevado
df2_alto = df2[
    df2['Consumo_kWh'] > limiar_75
]

# Registros com consumo elevado + fator de potência baixo
df2_atencao = df2[
    (df2['Consumo_kWh'] > limiar_75_df2) &
    (df2['Fator_Potencia_Atrasado'] < limite_fpa)
]

# Resultados
print(f"Maior consumo: {consumo_maximo:.2f} kWh")
print(f"Limiar de 75%: {limiar_75:.2f} kWh")
print(f"Limite do fator de potência: {limite_fpa}")
print(f"Registros com consumo elevado: {len(df2_alto)}")
print(f"Registros com consumo elevado + fator de potência baixo: {len(df2_atencao)}")

# Mostrar os registros encontrados
display(df2_atencao)

Maior consumo: 149.65 kWh
Limiar de 75%: 112.24 kWh
Limite do fator de potência: 0.9
Registros com consumo elevado: 167
Registros com consumo elevado + fator de potência baixo: 0

Empty DataFrame
Columns: [date, Consumo_kWh, Potencia_Reativa_Atrasada, Potencia_Reativa_Adiantada, Fator_Potencia_Atrasado, Fator_Potencia_Adiantado, WeekStatus, Day_of_week, Load_Type]
Index: []

# **Exercício 8**

Os registros com alto consumo e baixo fator de potência merecem atenção porque podem indicar maior demanda elétrica e menor eficiência no uso da energia, aumentando as perdas no sistema. Na amostra analisada, não foram encontrados registros que atendam simultaneamente aos dois critérios.

# **Dataset 3 — Power Consumption of Tetouan City (UCI)**
**Situação**

Uma equipe responsável pelo planejamento da distribuição de energia em Tétouan deseja
identificar qual das três zonas apresenta o maior pico de consumo e observar as condições
ambientais registradas nos momentos de maior demanda.

![untitled.svg]()

In [ ]:
df3 = pd.read_csv("/content/amostra_tetouan_15.csv")

In [ ]:
# Ver os nomes atuais
print(df3.columns.tolist())

# Remover espaços extras dos nomes
df3.columns = df3.columns.str.strip()

# Renomear as zonas
df3 = df3.rename(columns={
    "Zone 1 Power Consumption": "Consumo_Zona_1",
    "Zone 2  Power Consumption": "Consumo_Zona_2",
    "Zone 3  Power Consumption": "Consumo_Zona_3"
})

['DateTime', 'Temperature', 'Humidity', 'Wind Speed', 'Zone 1 Power Consumption', 'Zone 2  Power Consumption', 'Zone 3  Power Consumption']

In [ ]:
# Determinando consumo máximo
max_zona_1 = df3["Consumo_Zona_1"].max()
max_zona_2 = df3["Consumo_Zona_2"].max()
max_zona_3 = df3["Consumo_Zona_3"].max()

maximos = {
    "Zona 1": max_zona_1,
    "Zona 2": max_zona_2,
    "Zona 3": max_zona_3
}

zona_maior = max(maximos, key=maximos.get)

print("Máximo Zona 1:", max_zona_1)
print("Máximo Zona 2:", max_zona_2)
print("Máximo Zona 3:", max_zona_3)

print("\nZona com maior pico:", zona_maior)
print("Valor máximo:", maximos[zona_maior])

Máximo Zona 1: 51085.63818
Máximo Zona 2: 36429.6
Máximo Zona 3: 47254.9

Zona com maior pico: Zona 1
Valor máximo: 51085.63818

In [ ]:
# Calculando 70%
coluna_zona = {
    "Zona 1": "Consumo_Zona_1",
    "Zona 2": "Consumo_Zona_2",
    "Zona 3": "Consumo_Zona_3"
}[zona_maior]

valor_maximo = maximos[zona_maior]

limiar_df3 = valor_maximo * 0.70

print("Zona analisada:", zona_maior)
print("Valor máximo:", valor_maximo)
print("Limiar de 70%:", limiar)

Zona analisada: Zona 1
Valor máximo: 51085.63818
Limiar de 70%: 35759.946726

In [ ]:
df3_acima_limiar = df3[df3[coluna_zona] > limiar_df3]

print("Registros acima do limiar:")
display(df3_acima_limiar)

Registros acima do limiar:

,DateTime,Temperature,Humidity,Wind Speed,Consumo_Zona_1,Consumo_Zona_2,Consumo_Zona_3
0,2/14/2017 21:10,15.33,63.48,0.081,37391.18644,28909.4,25014.0
5,1/18/2017 20:30,14.84,56.03,0.082,43370.12658,28927.7,26937.8
7,10/16/2017 21:20,20.08,90.30,0.069,42443.76368,26350.2,18178.7
11,3/14/2017 21:20,13.29,77.90,0.070,41570.04255,25426.8,25310.3
14,8/31/2017 18:20,27.67,46.75,4.923,36023.97336,20885.3,16894.8
...,...,...,...,...,...,...,...
7850,5/15/2017 12:40,20.46,70.40,4.925,36045.63934,21050.2,19612.0
7853,3/9/2017 20:10,12.81,82.20,0.074,41668.08511,28741.5,25786.5
7854,10/8/2017 22:50,18.51,76.30,0.075,35814.09190,21155.6,16690.6
7855,3/7/2017 21:30,12.43,80.10,0.074,39707.23404,27596.3,24172.3
7860,2/12/2017 20:30,12.54,87.30,0.071,43425.76271,25955.0,26513.4

In [ ]:
# Calculando o registro e o percentual
quantidade = len(df3_acima_limiar)
total = len(df3)

percentual = (quantidade / total) * 100

print("Total de registros:", total)
print("Registros acima do limiar:", quantidade)
print("Percentual:", percentual, "%")

Total de registros: 7863
Registros acima do limiar: 2516
Percentual: 31.997965153249396 %

In [ ]:
# Caulculando a temperatura média
temperatura_media = df3["Temperature"].mean()

print("Temperatura média:", temperatura_media)

Temperatura média: 18.687388147017675

In [ ]:
df3_acima_limiar_temp = df3[
    (df3[coluna_zona] > limiar_df3) &
    (df3["Temperature"] > temperatura_media)
]

print("Registros com consumo acima do limiar e temperatura acima da média:")
display(df3_acima_limiar_temp)

Registros com consumo acima do limiar e temperatura acima da média:

,DateTime,Temperature,Humidity,Wind Speed,Consumo_Zona_1,Consumo_Zona_2,Consumo_Zona_3
7,10/16/2017 21:20,20.08,90.30,0.069,42443.76368,26350.2,18178.7
14,8/31/2017 18:20,27.67,46.75,4.923,36023.97336,20885.3,16894.8
17,9/8/2017 20:40,23.50,79.00,0.267,45716.81416,27494.0,23134.1
25,6/15/2017 14:50,25.75,36.67,0.072,36607.15232,23482.3,18993.2
27,8/17/2017 12:30,29.64,38.41,0.072,42973.05216,29100.3,27174.9
...,...,...,...,...,...,...,...
7827,6/17/2017 17:10,24.47,58.52,0.054,36772.45033,22868.6,21060.9
7829,9/20/2017 13:50,26.25,68.59,4.932,36879.29204,23362.6,13638.1
7834,9/19/2017 20:00,22.75,83.30,4.910,46653.45133,28302.3,21004.3
7849,8/28/2017 14:50,25.69,83.70,4.923,39162.88568,24291.4,19488.9
7850,5/15/2017 12:40,20.46,70.40,4.925,36045.63934,21050.2,19612.0

In [ ]:
print("Quantidade de registros:", len(df3_acima_limiar_temp))

Quantidade de registros: 1686

In [ ]:
# Comparação dos dois conjuntos
print("Registros acima do limiar:", len(df3_acima_limiar))
print("Registros acima do limiar + temperatura acima da média:", len(df3_acima_limiar_temp))

Registros acima do limiar: 2516
Registros acima do limiar + temperatura acima da média: 1686

In [ ]:
diferenca = len(df3_acima_limiar) - len(df3_acima_limiar_temp)

print("Quantidade de registros removidos:", diferenca)

Quantidade de registros removidos: 830

# **Questão 7**

Ao incluir a condição de temperatura acima da média, a quantidade de registros diminuiu em relação ao primeiro conjunto. Isso ocorreu porque, além de apresentar consumo acima de 70% do valor máximo, os registros também precisaram apresentar temperatura acima da média. Portanto, a inclusão da condição ambiental tornou o filtro mais restritivo.

# **Dataset 4 — Solar Power Generation Data (Kaggle)**
**Situação**

Uma equipe de operação de uma usina fotovoltaica deseja localizar períodos de alta geração e
identificar quais inversores aparecem com maior frequência nesses momentos. Nesta atividade, o
foco inicial será o arquivo de geração da planta, sem realizar junção com o arquivo de sensores

![untitled.svg]()

In [ ]:
df4 = pd.read_csv("/content/Plant_1_Generation_Data_20.csv")

In [ ]:
df4.head()

,DATE_TIME,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
0,10-06-2020 19:00,uHbuxQJl8lW7ozc,0.00,0.000,6645.000,7240508.000
1,28-05-2020 00:15,rGa61gmuvPhdLxV,0.00,0.000,0.000,7206549.000
2,17-05-2020 15:15,sjndEbLyjtCKgGv,7333.88,718.062,6442.000,7036055.000
3,01-06-2020 04:15,ih0vzX44oOqAx2f,0.00,0.000,0.000,6308232.000
4,17-05-2020 09:00,z9Y9gH1T5YWrNuG,7665.50,750.438,961.375,7021701.375

In [ ]:
# Renomeando variáveis
df4 = df4.rename(columns={
    "DATE_TIME": "Data_Hora",
    "SOURCE_KEY": "Inversor",
    "DC_POWER": "Potencia_CC",
    "AC_POWER": "Potencia_CA",
    "DAILY_YIELD": "Geracao_Diaria",
    "TOTAL_YIELD": "Geracao_Total"
})

df4.head()

,Data_Hora,Inversor,Potencia_CC,Potencia_CA,Geracao_Diaria,Geracao_Total
0,10-06-2020 19:00,uHbuxQJl8lW7ozc,0.00,0.000,6645.000,7240508.000
1,28-05-2020 00:15,rGa61gmuvPhdLxV,0.00,0.000,0.000,7206549.000
2,17-05-2020 15:15,sjndEbLyjtCKgGv,7333.88,718.062,6442.000,7036055.000
3,01-06-2020 04:15,ih0vzX44oOqAx2f,0.00,0.000,0.000,6308232.000
4,17-05-2020 09:00,z9Y9gH1T5YWrNuG,7665.50,750.438,961.375,7021701.375

In [ ]:
# Apresentando head(), shape, info() e describe()
print("Primeiros registros:")
display(df4.head())

print("\nDimensões:")
print(df4.shape)

print("\nInformações:")
df4.info()

print("\nEstatísticas:")
display(df4.describe())

Primeiros registros:

,Data_Hora,Inversor,Potencia_CC,Potencia_CA,Geracao_Diaria,Geracao_Total
0,10-06-2020 19:00,uHbuxQJl8lW7ozc,0.00,0.000,6645.000,7240508.000
1,28-05-2020 00:15,rGa61gmuvPhdLxV,0.00,0.000,0.000,7206549.000
2,17-05-2020 15:15,sjndEbLyjtCKgGv,7333.88,718.062,6442.000,7036055.000
3,01-06-2020 04:15,ih0vzX44oOqAx2f,0.00,0.000,0.000,6308232.000
4,17-05-2020 09:00,z9Y9gH1T5YWrNuG,7665.50,750.438,961.375,7021701.375

Dimensões:
(13756, 6)

Informações:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13756 entries, 0 to 13755
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Data_Hora       13756 non-null  object
 1   Inversor        13756 non-null  object
 2   Potencia_CC     13756 non-null  float64
 3   Potencia_CA     13756 non-null  float64
 4   Geracao_Diaria  13756 non-null  float64
 5   Geracao_Total   13756 non-null  float64
dtypes: float64(4), object(2)
memory usage: 644.9+ KB

Estatísticas:

        Potencia_CC   Potencia_CA  Geracao_Diaria  Geracao_Total
count  13756.000000  13756.000000    13756.000000   1.375600e+04
mean    3135.848662    306.695495     3319.235216   6.978829e+06
std     4023.069619    393.124284     3142.249927   4.162164e+05
min        0.000000      0.000000        0.000000   6.183645e+06
25%        0.000000      0.000000        0.000000   6.509779e+06
50%      370.071500     35.771400     2730.425000   7.146218e+06
75%     6350.562500    622.065500     6293.782500   7.267996e+06
max    14416.100000   1405.590000     9163.000000   7.846821e+06

In [ ]:
# Determinar a maior potência CA
max_potencia_ca = df4["Potencia_CA"].max()

print("Maior potência CA:", max_potencia_ca)

Maior potência CA: 1405.59

In [ ]:
# Calculando o limite de 70%
limiar_df4 = max_potencia_ca * 0.70

print("Limiar de alta geração:", limiar)

Limiar de alta geração: 35759.946726

In [ ]:
df4_alta_geracao = df4[df4["Potencia_CA"] > limiar_df4]

print("Quantidade de registros de alta geração:", len(df4_alta_geracao))

Quantidade de registros de alta geração: 1185

In [ ]:
percentual = (len(df4_alta_geracao) / len(df4)) * 100

print(f"Percentual de registros de alta geração: {percentual:.2f}%")

Percentual de registros de alta geração: 8.61%

In [ ]:
df4_alta_geracao.head()

,Data_Hora,Inversor,Potencia_CC,Potencia_CA,Geracao_Diaria,Geracao_Total
11,26-05-2020 12:15,bvBOhCH3iADSZry,11830.1,1153.83,4028.14,6396364.143
46,15-06-2020 14:30,wCURE6d3bPkepu2,10571.3,1032.07,5366.57,7015064.571
48,25-05-2020 10:15,z9Y9gH1T5YWrNuG,11050.1,1079.86,2174.29,7082812.286
72,13-06-2020 11:30,7JYdWkrLSPkdwr4,11094.5,1082.44,3570.25,7815987.250
76,07-06-2020 13:00,VHMLBKoKgIrUVDU,12663.4,1234.69,4976.71,7382965.714

In [ ]:
# Utilizando value_counts()
contagem_inversores = df4_alta_geracao["Inversor"].value_counts()

print(contagem_inversores)

Inversor
adLQvlD726eNBSB    68
McdE0feGgRqW7Ca    65
ZnxXDlPa8U1GXgE    63
pkci93gMrogZuBj    62
ZoEaEvLYb1n2sOq    61
1IF53ai7Xc0U56Y    59
YxYtjZvoooNbGkE    58
sjndEbLyjtCKgGv    57
z9Y9gH1T5YWrNuG    56
uHbuxQJl8lW7ozc    55
zVJPv84UY57bAof    54
zBIq5rxdHJRwDNY    53
ih0vzX44oOqAx2f    53
WRmjgnKYAwPKWDb    52
3PZuoBAID5Wc2HD    51
iCRJl6heRkivqQ3    51
VHMLBKoKgIrUVDU    51
wCURE6d3bPkepu2    49
rGa61gmuvPhdLxV    43
7JYdWkrLSPkdwr4    43
1BY6WEcLGh8j5v7    42
bvBOhCH3iADSZry    39
Name: count, dtype: int64

In [ ]:
inversor_mais_frequente = df4_alta_geracao["Inversor"].value_counts().idxmax()
quantidade_df4 = df4_alta_geracao["Inversor"].value_counts().max()

print("Inversor mais frequente:", inversor_mais_frequente)
print("Quantidade de registros:", quantidade_df4)

Inversor mais frequente: adLQvlD726eNBSB
Quantidade de registros: 68

# **Questão 7**

O inversor que aparece com maior frequência nos registros de alta geração foi o que apresentou a maior quantidade de ocorrências acima do limite de 70% da potência CA máxima. Esse resultado permite identificar quais inversores aparecem mais frequentemente nos períodos de alta geração da amostra. Entretanto, esse recorte não é suficiente para concluir que o inversor possui melhor desempenho ou que os demais apresentam falhas, pois seria necessário analisar outros períodos e fatores.

# **Dataset 5 — Wind & Solar Energy Production (Kaggle)**
**Situação**

Um operador de um portfólio de fontes renováveis deseja comparar a ocorrência de períodos de
alta produção solar e alta produção eólica. Como as duas fontes possuem escalas próprias, cada
uma deverá ser comparada com o seu próprio valor máximo.

In [ ]:
df5 = pd.read_csv("/content/Energy_Production_Dataset_20.csv")

![untitled.svg]()

In [ ]:
df5.head()

,Date,Start_Hour,End_Hour,Day_of_Year,Production,Source
0,string,continuous,continuous,continuous,continuous,Mixed Solar Wind
1,meta,NaN,NaN,NaN,NaN,NaN
2,12/18/2022,21,22,352,11400,Wind
3,1/29/2024,14,15,29,7917,Wind
4,8/1/2024,15,16,214,8835,Solar

In [ ]:
# Renomeando
print(df5.columns)

Index(['Date', 'Start_Hour', 'End_Hour', 'Day_of_Year', 'Production',
       'Source'],
      dtype='object')

In [ ]:
df5['Source'].unique()

array(['Mixed Solar Wind', nan, 'Wind', 'Solar'], dtype=object)

In [ ]:
df5_solar = df5[df5['Source'] == 'Solar'].copy()
df5_eolica = df5[df5['Source'] == 'Wind'].copy()

In [ ]:
df5_solar = df5_solar.rename(columns={'Production': 'Geracao_Solar'})
df5_eolica = df5_eolica.rename(columns={'Production': 'Geracao_Eolica'})

In [ ]:
max_solar = df5_solar['Geracao_Solar'].max()
max_eolica = df5_eolica['Geracao_Eolica'].max()

print("Máximo de geração solar:", max_solar)
print("Máximo de geração eólica:", max_eolica)

Máximo de geração solar: 9997
Máximo de geração eólica: 9998

In [ ]:
df5_solar.head()

          Date Start_Hour End_Hour Day_of_Year Geracao_Solar Source
4     8/1/2024         15       16         214          8835  Solar
7   10/18/2024         13       14         292          4855  Solar
8    4/10/2020         17       18         101          3692  Solar
15    6/2/2021         15       16         153          5561  Solar
18    5/2/2021         13       14         122          4993  Solar

In [ ]:
df5_eolica.head()

         Date Start_Hour End_Hour Day_of_Year Geracao_Eolica Source
2  12/18/2022         21       22         352          11400   Wind
3   1/29/2024         14       15          29           7917   Wind
5  11/10/2020          1        2         315            989   Wind
6  12/19/2022          1        2         353          12526   Wind
9   1/25/2023          0        1          25           2156   Wind

In [ ]:
# Encontrando os máximos
df5_solar['Geracao_Solar'] = pd.to_numeric(
    df5_solar['Geracao_Solar'], errors='coerce'
)

df5_eolica['Geracao_Eolica'] = pd.to_numeric(
    df5_eolica['Geracao_Eolica'], errors='coerce'
)

In [ ]:
max_solar = df5_solar['Geracao_Solar'].max()
max_eolica = df5_eolica['Geracao_Eolica'].max()

print("Máximo solar:", max_solar)
print("Máximo eólico:", max_eolica)

Máximo solar: 16316
Máximo eólico: 22929

In [ ]:
# Calculando 70% dos máximos
limite_solar = max_solar * 0.70
limite_eolica = max_eolica * 0.70

print("70% do máximo solar:", limite_solar)
print("70% do máximo eólico:", limite_eolica)

70% do máximo solar: 11421.199999999999
70% do máximo eólico: 16050.3

In [ ]:
# Crinado os DatasFrames
limite_solar = max_solar * 0.70
limite_eolica = max_eolica * 0.70

alta_solar = df5_solar[df5_solar['Geracao_Solar'] >= limite_solar].copy()
alta_eolica = df5_eolica[df5_eolica['Geracao_Eolica'] >= limite_eolica].copy()

print("Registros de alta geração solar:", len(alta_solar))
print("Registros de alta geração eólica:", len(alta_eolica))

Registros de alta geração solar: 45
Registros de alta geração eólica: 245

In [ ]:
qtd_solar = len(alta_solar)
qtd_eolica = len(alta_eolica)

total_solar = len(df5_solar)
total_eolica = len(df5_eolica)

percentual_solar = (qtd_solar / total_solar) * 100
percentual_eolica = (qtd_eolica / total_eolica) * 100

print(f"Solar: {qtd_solar} registros ({percentual_solar:.2f}%)")
print(f"Eólica: {qtd_eolica} registros ({percentual_eolica:.2f}%)")

Solar: 45 registros (2.44%)
Eólica: 245 registros (2.87%)

In [ ]:
# Comparando as fontes
if percentual_solar > percentual_eolica:
    print("A geração solar aparece com maior frequência acima de 70% do próprio máximo.")
elif percentual_eolica > percentual_solar:
    print("A geração eólica aparece com maior frequência acima de 70% do próprio máximo.")
else:
    print("As duas fontes apresentam a mesma frequência.")

A geração eólica aparece com maior frequência acima de 70% do próprio máximo.

# **Questão 7**

Não é adequado utilizar o mesmo valor numérico como limite para as duas fontes, pois elas possuem escalas de geração diferentes. Neste caso, 70% do máximo solar corresponde a 11.421,20, enquanto 70% do máximo eólico corresponde a 16.050,30. Portanto, cada fonte deve ser comparada com seu próprio máximo.

# **Dataset 6 — Individual Household Electric Power Consumption (UCI)**

**Situação**

Uma residência possui monitoramento elétrico detalhado e deseja identificar episódios de
demanda elevada que também apresentem corrente acima do comportamento médio. O dataset é
o mesmo utilizado como referência em aula, mas o critério de análise será diferente

![untitled.svg]()

In [ ]:
#  Renomeando as colunas
df6 = pd.read_csv("/content/household_power_consumption.csv")

df6 = df6.rename(columns={
    "Global_active_power": "Potencia_Ativa",
    "Global_reactive_power": "Potencia_Reativa",
    "Voltage": "Tensao",
    "Global_intensity": "Corrente",
    "Sub_metering_1": "Submetering_1",
    "Sub_metering_2": "Submetering_2",
    "Sub_metering_3": "Submetering_3"
})

df6.head()

,Potencia_Ativa,Potencia_Reativa,Tensao,Corrente,Submetering_1,Submetering_2,Submetering_3
0,0.256,0.106,242.00,1.2,0.0,0.0,1.0
1,0.466,0.352,237.22,2.4,0.0,2.0,0.0
2,0.758,0.194,238.66,3.2,0.0,1.0,0.0
3,1.290,0.046,240.64,5.4,1.0,0.0,18.0
4,0.428,0.202,242.23,1.8,0.0,2.0,1.0

In [ ]:
#  Encontrando a potência ativa máxima
max_potencia = df6["Potencia_Ativa"].max()

print("Potência ativa máxima:", max_potencia)

Potência ativa máxima: 10.65

In [ ]:
# Calculando 75% do máximo
limite_75_df6 = max_potencia * 0.75

print("Limite de 75%:", limite_75_df6)

Limite de 75%: 7.987500000000001

In [ ]:
# Crinado um DataFrame pra 75%
df6_alta_potencia = df6[df6["Potencia_Ativa"] > limite_75_df6]

df6_alta_potencia.head()

,Potencia_Ativa,Potencia_Reativa,Tensao,Corrente,Submetering_1,Submetering_2,Submetering_3
24635,8.110,0.196,236.87,34.2,37.0,74.0,17.0
42771,8.026,0.058,234.91,34.0,37.0,73.0,17.0
45962,8.218,0.336,236.05,34.8,37.0,73.0,17.0
46828,9.708,0.372,231.37,42.0,37.0,69.0,17.0
55667,8.168,0.540,228.91,35.6,35.0,35.0,17.0

In [ ]:
# Quantidade e percentual dos registros
quantidade_alta = len(df6_alta_potencia)

print("Quantidade de registros:", quantidade_alta)

Quantidade de registros: 33

In [ ]:
percentual_alta = (quantidade_alta / len(df6)) * 100

print("Percentual de registros:", percentual_alta, "%")

Percentual de registros: 0.015901621965440475 %

In [ ]:
# Calculando a corrente média
corrente_media = df6["Corrente"].mean()

print("Corrente média:", corrente_media)

Corrente média: 4.637612176280848

In [ ]:
# Criando segundo DataFrame
df6_alta_potencia_corrente = df6[
    (df6["Potencia_Ativa"] > limite_75_df6) &
    (df6["Corrente"] > corrente_media)
]

df6_alta_potencia_corrente.head()

,Potencia_Ativa,Potencia_Reativa,Tensao,Corrente,Submetering_1,Submetering_2,Submetering_3
24635,8.110,0.196,236.87,34.2,37.0,74.0,17.0
42771,8.026,0.058,234.91,34.0,37.0,73.0,17.0
45962,8.218,0.336,236.05,34.8,37.0,73.0,17.0
46828,9.708,0.372,231.37,42.0,37.0,69.0,17.0
55667,8.168,0.540,228.91,35.6,35.0,35.0,17.0

In [ ]:
# Comparando os dois DataFrames
print("Registros com potência acima de 75%:", len(df6_alta_potencia))

print("Registros com potência acima de 75% e corrente acima da média:",
      len(df6_alta_potencia_corrente))

Registros com potência acima de 75%: 33
Registros com potência acima de 75% e corrente acima da média: 33

In [ ]:
percentual_dupla_condicao = (
    len(df6_alta_potencia_corrente) / len(df6)
) * 100

print("Percentual com as duas condições:",
      percentual_dupla_condicao, "%")

Percentual com as duas condições: 0.015901621965440475 %

# **Questão 7**

Ao considerar apenas a potência ativa acima de 75% do máximo, foram selecionados mais registros. Ao adicionar a condição de corrente acima da média, o número de registros diminuiu, pois agora os dados precisam atender simultaneamente às duas condições. Dessa forma, a segunda condição torna a seleção mais restritiva, identificando períodos de alta demanda que também apresentam corrente elevada.